2018-11-10 15:55:57,982 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
2018-11-10 16:01:56,936 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
2018-11-10 16:02:10,299 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
2018-11-10 16:05:39,873 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
2018-11-10 16:09:05,912 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
2018-11-10 16:09:34,545 ERROR: Exception on /user/edit/1010 [GET] [in D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\GitHub\mycode\recruitment\app\main\user\views.py", line 65, in user_edit
    form = EditUserForm(user=user)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
  File "E:\GitHub\mycode\recruitment\app\main\user\forms.py", line 83, in __init__
    super(EditUserForm, self).__init__(*args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'user'
2018-11-10 16:11:43,826 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
2018-11-10 16:11:49,666 ERROR: Exception on /user/edit/1010 [GET] [in D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "E:\GitHub\mycode\recruitment\app\main\user\views.py", line 109, in user_edit
    return render_template('main/user/edit.html', form=form, user=user)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "E:\GitHub\mycode\recruitment\app\templates\main\user\edit.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "E:\GitHub\mycode\recruitment\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block "body"
    {% block content -%}
  File "E:\GitHub\mycode\recruitment\app\templates\base.html", line 73, in block "content"
    {% block app_content %}{% endblock %}
  File "E:\GitHub\mycode\recruitment\app\templates\main\user\edit.html", line 12, in block "app_content"
    {{ wtf.quick_form(form, form_type="horizontal") }}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 205, in template
    {{ form_field(field,
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\jinja2\runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 104, in template
    {{field(class="form-control", **kwargs)|safe}}
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\wtforms\fields\core.py", line 155, in __call__
    return self.meta.render_field(self, kwargs)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\wtforms\meta.py", line 56, in render_field
    return field.widget(field, **render_kw)
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\wtforms\widgets\core.py", line 323, in __call__
    for val, label, selected in field.iter_choices():
  File "D:\Develop\Anaconda\envs\py37\lib\site-packages\wtforms\fields\core.py", line 454, in iter_choices
    for value, label in self.choices:
TypeError: 'NoneType' object is not iterable
2018-11-10 16:14:04,389 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
2018-11-10 16:14:43,251 INFO: 公司后台 startup [in E:\GitHub\mycode\recruitment\app\__init__.py:85]
